[features]
seeds = false
skip-lint = false
[programs.localnet]
calculator = "4R6YqfBNVnjaohhXGxviSuz3wMuuZ7ZxY7GxmSVxm5ah"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/davie/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
